#  useing travis to build production

sudo: required
services:
  - docker
# build image for testing for react app
before_install:
  - docker build -t toatpor/react-test -f ./client/Dockerfile.dev ./client

# test running section
script:
  - docker run -e CI=true toatpor/react-test npm run test

#  build production image for each one
after_success:
  - docker build -t toatpor/multi-client ./client
  - docker build -t toatpor/multi-api ./api
  - docker build -t toatpor/multi-nginx ./nginx
  - docker build -t toatpor/multi-worker ./worker
  # log in docker li
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #  tale those images and push them to docker hub
  - docker push toatpor/multi-client
  - docker push toatpor/multi-api
  - docker push toatpor/multi-nginx
  - docker push toatpor/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: multi-docker
  env: Multi-docker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-637423331546
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
