version: "3"
services:
  client:
    image: "rallycoding/multi-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "rallycoding/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=multi-docker-redis.1tqdw1.ng.0001.apse2.cache.amazonaws.com
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=multi-docker-postgres.cpkm2g2kwtvd.ap-southeast-2.rds.amazonaws.com
      - PGDATABASE=fibvalues
      - PGPASSWORD=postgrespassword
      - PGPORT=5432
  worker:
    image: "rallycoding/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=multi-docker-redis.1tqdw1.ng.0001.apse2.cache.amazonaws.com
      - REDIS_PORT=6379
  nginx:
    image: "rallycoding/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
